FROM openjdk:11-jre-slim

WORKDIR /app
COPY build/libs/*.jar app.jar

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG GOOGLE_MAPS_API_KEY
ARG BUCKET_NAME
ARG IAM_ACCESS_KEY
ARG IAM_SECRET_KEY
ARG SECRET_KEY
ARG REFRESH_KEY

ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
ENV BUCKET_NAME=$BUCKET_NAME
ENV IAM_ACCESS_KEY=$IAM_ACCESS_KEY
ENV IAM_SECRET_KEY=$IAM_SECRET_KEY
ENV SECRET_KEY=$SECRET_KEY
ENV REFRESH_KEY=$REFRESH_KEY

CMD ["java", "-jar", "app.jar"]
