FROM openjdk:11-jre-slim

WORKDIR /app
COPY build/libs/*.jar app.jar

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG GOOGLE_MAPS_API_KEY
ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY

CMD ["java", "-jar", "app.jar"]
