name: Build Docker Image (Main)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug Docker Hub credentials
        run:
          echo "DOCKER_USERNAME:
            ${{ secrets.DOCKER_USERNAME }}, DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"


      - name: Debug build.gradle content
        run: cat build.gradle

      - name: Debug version
        run: echo "Version is ${{ steps.get_version.outputs.version }}"

      - name: Get version from build.gradle
        id: get_version
        run: echo "::set-output name=version::$(cat build.gradle | grep version | awk '{print $2}' | sed 's/\"//g')"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            yunki0415/room-backend:${{ steps.get_version.outputs.version }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
