name: Build Docker Image (Main)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug Docker Hub credentials
        run: echo "DOCKER_USERNAME - ${{ secrets.DOCKERHUB_USERNAME }}"


      - name: Debug build.gradle content
        run: cat build.gradle

      - name: Debug version
        run: echo "Version is ${{ steps.get_version.outputs.version }}"

      - name: Get version from build.gradle
        id: get_version
        run: echo "::set-output name=version::$(awk -F= '/^version/ {print $2}' build.gradle | tr -d '[:space:]' | tr -d "'")"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            yunki0415/room-backend:${{ steps.get_version.outputs.version }}
          build-args: |
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            IAM_ACCESS_KEY=${{ secrets.IAM_ACCESS_KEY}}
            IAM_SECRET_KEY=${{ secrets.IAM_SECRET_KEY }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            REFRESH_KEY=${{ secrets.REFRESH_KEY }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
